package com.brewpubs.app.models;

/**
 * Created by Rajiv Shankar on 11/14/25 @ 12:07 PM.
 */

/**
 * MODEL LAYER
 * POJO (Plain Old Java Object) to represent a brewery, just holds data - no special behavior (all pojos are models but not vv)
 */

/**
 * Brewery model - maps to BREWERIES table
 *
 * FIELD NAMING CONVENTION:
 * - Java uses camelCase: breweryId, signatureBeer
 * - Database uses snake_case: brewery_id, signature_beer
 * - MyBatis maps automatically with map-underscore-to-camel-case=true
 */

public class Brewery {

    // Primary key - auto-generated by database
    private Integer breweryId;
    private String name;
    private String address;
    private String signatureBeer;

    // Default constructor - REQUIRED for MyBatis; MyBatis creates objects using reflection, then calls setters
    // MyBatis creates empty objects then calls setters
    public Brewery() { }

    // Constructor for creating new breweries (without ID)
    public Brewery(String name, String address, String signatureBeer) { // constructor to initialize brewery data
        this.name = name;
        this.address = address;
        this.signatureBeer = signatureBeer;
    }

    // Full constructor (including ID) - used when loading from database
    public Brewery(Integer breweryId, String name, String address, String signatureBeer) {
        this.breweryId = breweryId;
        this.name = name;
        this.address = address;
        this.signatureBeer = signatureBeer;
    }

    // ========== GETTERS AND SETTERS ==========
    // Thymeleaf uses these to access the data in templates; MyBatis REQUIRES setters to populate objects from database

    public Integer getBreweryId() {
        return breweryId;
    }

    public void setBreweryId(Integer breweryId) {
        this.breweryId = breweryId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getSignatureBeer() {
        return signatureBeer;
    }

    public void setSignatureBeer(String signatureBeer) {
        this.signatureBeer = signatureBeer;
    }

    @Override
    public String toString() {
        return "Brewery{" +
                "breweryId=" + breweryId +
                ", name='" + name + '\'' +
                ", address='" + address + '\'' +
                ", signatureBeer='" + signatureBeer + '\'' +
                '}';
    }
}
