package com.brewpubs.app.models;

/**
 * Created by Rajiv Shankar on 1/21/26 @ 3:14 PM.
 */

/**
 * Credential model - maps to CREDENTIALS table
 *
 * PRACTICE MODEL for learning encryption/decryption
 * (Same pattern will be used in SuperDuperDrive)
 *
 * ENCRYPTION STRATEGY:
 * - password: Stored as ENCRYPTED text in database
 * - encryptionKey: Encryption key generated for this credential
 * - EncryptionService handles encrypt/decrypt
 *
 * SECURITY FLOW:
 * 1. User enters plain text password in form
 * 2. CredentialService generates random encryption key
 * 3. EncryptionService.encryptValue(plainPassword, encryptionKey) → encrypted password
 * 4. Store encrypted password + encryptionKey in database
 * 5. List view: Display encrypted password (user can't read it)
 * 6. Edit modal: Decrypt password for editing (call EncryptionService.decryptValue())
 *
 * ENCRYPTION vs HASHING:
 * - User passwords (USERS table): HASHED (one-way, can't reverse)
 * - Credential passwords (CREDENTIALS table): ENCRYPTED (two-way, can decrypt)
 * - Hashing = verify login; Encryption = store retrievable passwords
 */
public class Credential {

    private Integer credentialId;  // Auto-generated by database
    private String url;            // Website URL (e.g., "https://example.com")
    private String username;       // Username for that site
    private String encryptionKey;  // Encryption key for this credential
    private String password;       // Encrypted password (NOT plain text!)
    private Integer userId;        // Foreign key to USERS table

    // ========== CONSTRUCTORS ==========

    // Default no-args constructor - REQUIRED for MyBatis
    public Credential() { }

    // Constructor for creating new credentials (without credentialId)
    public Credential(String url, String username, String encryptionKey, String password, Integer userId) {
        this.url = url;
        this.username = username;
        this.encryptionKey = encryptionKey;
        this.password = password;
        this.userId = userId;
    }

    // Full constructor (including credentialId) - used when loading from database
    public Credential(Integer credentialId, String url, String username, String encryptionKey, String password, Integer userId) {
        this.credentialId = credentialId;
        this.url = url;
        this.username = username;
        this.encryptionKey = encryptionKey;
        this.password = password;
        this.userId = userId;
    }

    // ========== GETTERS AND SETTERS ==========

    public Integer getCredentialId() {
        return credentialId;
    }

    public void setCredentialId(Integer credentialId) {
        this.credentialId = credentialId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEncryptionKey() {
        return encryptionKey;
    }

    public void setEncryptionKey(String encryptionKey) {
        this.encryptionKey = encryptionKey;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "Credential{" +
                "credentialId=" + credentialId +
                ", url='" + url + '\'' +
                ", username='" + username + '\'' +
                ", userId=" + userId +
                '}';  // Don't log password or encryptionKey for security
    }
}


