package com.brewpubs.app.models;

// ––––– Created by Rajiv Shankar on 1/21/26 @ 3:05 PM ––––– //

/**
 * File model - maps to FILES table
 *
 * PRACTICE MODEL for learning file upload/download
 * (Same pattern will be used in SuperDuperDrive)
 *
 * IMPORTANT: This class name conflicts with java.io.File
 * Always import fully qualified name or rename to UserFile if issues arise
 *
 * FILE STORAGE STRATEGY:
 * - fileData: Binary content stored as byte[] (BLOB in database)
 * - filename: Original name like "report.pdf"
 * - contentType: MIME type like "application/pdf", "image/png"
 * - fileSize: Size in bytes (string for simplicity)
 *
 * DUPLICATE PREVENTION:
 * - Service layer will check: does this userId already have this filename?
 * - Prevents uploading same file twice per user
 */
public class File {

    private Integer fileId;      // Auto-generated by database
    private String filename;     // Original filename (e.g., "report.pdf")
    private String contentType;  // MIME type (e.g., "application/pdf")
    private String fileSize;     // Size in bytes (stored as string)
    private byte[] fileData;     // Binary file content
    private Integer userId;      // Foreign key to USERS table

    // ========== CONSTRUCTORS ==========

    // Default no-args constructor - REQUIRED for MyBatis
    public File() { }

    // Constructor for creating new files (without fileId)
    public File(String filename, String contentType, String fileSize, byte[] fileData, Integer userId) {
        this.filename = filename;
        this.contentType = contentType;
        this.fileSize = fileSize;
        this.fileData = fileData;
        this.userId = userId;
    }

    // Full constructor (including fileId) - used when loading from database
    public File(Integer fileId, String filename, String contentType, String fileSize, byte[] fileData, Integer userId) {
        this.fileId = fileId;
        this.filename = filename;
        this.contentType = contentType;
        this.fileSize = fileSize;
        this.fileData = fileData;
        this.userId = userId;
    }

    // ========== GETTERS AND SETTERS ==========

    public Integer getFileId() {
        return fileId;
    }

    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getFileSize() {
        return fileSize;
    }

    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    public byte[] getFileData() {
        return fileData;
    }

    public void setFileData(byte[] fileData) {
        this.fileData = fileData;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "File{" +
                "fileId=" + fileId +
                ", filename='" + filename + '\'' +
                ", contentType='" + contentType + '\'' +
                ", fileSize='" + fileSize + '\'' +
                ", userId=" + userId +
                '}';  // Don't log fileData (too large)
    }
}


