package com.brewpubs.app.models;

// ––––– Created by Rajiv Shankar on 1/21/26 @ 3:01 PM ––––– //

/**
 * Note model - maps to NOTES table
 *
 * PRACTICE MODEL for learning CRUD operations
 * (Same pattern will be used in SuperDuperDrive)
 *
 * FIELD NAMING CONVENTION:
 * - Java uses camelCase: noteId, userId
 * - Database uses snake_case: note_id, user_id
 * - MyBatis maps automatically with map-underscore-to-camel-case=true
 *
 * VALIDATION:
 * - Title max 20 chars (SuperDuperDrive spec)
 * - Description max 1000 chars
 * - Both required (NOT NULL in database)
 */
public class Note {

    private Integer noteId;      // Auto-generated by database
    private String title;        // Max 20 characters
    private String description;  // Max 1000 characters
    private Integer userId;      // Foreign key to USERS table

    // ========== CONSTRUCTORS ==========

    // Default no-args constructor - REQUIRED for MyBatis
    public Note() { }

    // Constructor for creating new notes (without noteId)
    public Note(String title, String description, Integer userId) {
        this.title = title;
        this.description = description;
        this.userId = userId;
    }

    // Full constructor (including noteId) - used when loading from database
    public Note(Integer noteId, String title, String description, Integer userId) {
        this.noteId = noteId;
        this.title = title;
        this.description = description;
        this.userId = userId;
    }

    // ========== GETTERS AND SETTERS ==========
    // MyBatis REQUIRES setters to populate objects from database
    // Controllers use getters to access data for display

    public Integer getNoteId() {
        return noteId;
    }

    public void setNoteId(Integer noteId) {
        this.noteId = noteId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "Note{" +
                "noteId=" + noteId +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", userId=" + userId +
                '}';
    }
}


