package com.brewpubs.app.models;

/**
 * Created by Rajiv Shankar on 11/19/25 @ 11:22 AM.
 */

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * `User` model class (domain class = entity = POJO) representing a registered `user`
 *
 * PURPOSE: Hold user data that will be bound from HTML form
 *
 * BINDING PROCESS:
 * 1. User fills form in register.html
 * 2. Form submits to POST /register
 * 3. Spring creates User object
 * 4. Spring sets fields from form (via @ModelAttribute)
 * 5. Controller receives populated User object
 *
 * FIELDS:
 * - userId: Auto-generated primary key (from database)
 * - username: Login identifier (must be unique)
 * - salt: Random string for password hashing (generated on signup)
 * - password: HASHED password (never store plain text!)
 * - firstName, lastName: Optional user details
 * - email: For display/contact (not used for login)
 *
 * VALIDATION:
 * - @NotBlank on username, password (required for signup)
 * - @Size on password (minimum 4 characters)
 * - salt is NOT validated (generated by system, not user input)
 */

public class User {
    private Integer userId;  // Auto-generated by database

    @NotBlank(message = "Username is required")
    private String username;

    private String salt;  // Generated by HashService, not user input

    @NotBlank(message = "Password is required")
    @Size(min = 4, message = "Password must be at least 4 characters")
    private String password;

    private String firstName;
    private String lastName;

    @NotBlank(message = "Email is required")
    @Email(message = "Email must be valid")
    private String email;

    // Default no-args constructor - required for MyBatis and Spring form binding
    public User() { }

    // Constructor with all fields used when creating User objects programmatically
    public User(String username, String email) {
        this.username = username;
        this.email = email;
    }

    // ========== GETTERS AND SETTERS (required for @ModelAttribute binding) ==========


    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", username='" + username + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                '}';  // Never log password or salt!
    }
}

